#!/usr/bin/env node
/**
 * Acceptance matrix generator (CS-018, QA-01).
 *
 *   node scripts/acceptance-matrix.mjs          # write docs/testing/acceptance-matrix.md
 *   node scripts/acceptance-matrix.mjs --check  # exit 1 if any ID is unaccounted for
 *
 * Every acceptance ID from the issues (docs/testing/acceptance-ids.json) must be
 * either referenced by at least one automated test (the ID appears in a test
 * title or comment) or listed in docs/testing/acceptance-status.json with an
 * explicit status, owner and reason. Nothing is silently missing. A listed
 * blocker is not a pass: the matrix says so.
 */
import { execFileSync } from 'node:child_process';
import { readFileSync, writeFileSync } from 'node:fs';

const NUL = String.fromCharCode(0);
const ids = JSON.parse(readFileSync('docs/testing/acceptance-ids.json', 'utf8'));
const status = JSON.parse(readFileSync('docs/testing/acceptance-status.json', 'utf8'));

const tests = execFileSync('git', ['ls-files', '-z', '--cached', '--others', '--exclude-standard', 'tests'], { encoding: 'utf8' })
  .split(NUL)
  .filter((f) => /\.(test|spec)\.tsx?$/.test(f));

const coverage = new Map();
for (const file of tests) {
  const text = readFileSync(file, 'utf8');
  for (const id of Object.keys(ids)) {
    const re = new RegExp(`\\b${id.replace('-', '-')}\\b`);
    if (re.test(text)) coverage.set(id, [...(coverage.get(id) ?? []), file]);
  }
}

const tierOf = (file) => (file.startsWith('tests/e2e/') ? 'T1' : 'T0');
const rows = [];
const problems = [];
for (const [id, meta] of Object.entries(ids)) {
  const files = coverage.get(id) ?? [];
  const s = status[id];
  let state;
  if (s) state = s.status;
  else if (files.length > 0) state = 'automated';
  else {
    state = 'MISSING';
    problems.push(id);
  }
  rows.push({ id, meta, files, s, state });
}

if (process.argv.includes('--check')) {
  if (problems.length) {
    console.error(`acceptance matrix: ${problems.length} unaccounted ID(s): ${problems.join(', ')}`);
    process.exit(1);
  }
  console.log(`acceptance matrix: all ${rows.length} IDs accounted for`);
  process.exit(0);
}

const counts = rows.reduce((acc, r) => ((acc[r.state] = (acc[r.state] ?? 0) + 1), acc), {});
const esc = (t) => String(t).replace(/\|/g, '\\|');
const lines = [
  '# Acceptance matrix',
  '',
  'Generated by `node scripts/acceptance-matrix.mjs` from the issue acceptance IDs (`acceptance-ids.json`), the test suite and the explicit status file (`acceptance-status.json`). Do not edit by hand.',
  '',
  '**Automated** means at least one T0 (unit/integration, synthetic) or T1 (browser journey, synthetic) test names the ID and runs in CI on every PR. It is not T2 physical-device, T3 copied-live-data or T4 production evidence. **Blocked**, **deferred** and **manual** rows are not passes.',
  '',
  `Totals: ${Object.entries(counts)
    .map(([k, v]) => `${k} ${v}`)
    .join(' · ')} (of ${rows.length}).`,
  '',
  '| ID | Issue | Criterion | Status | Evidence | Residual risk / owner |',
  '| --- | --- | --- | --- | --- | --- |',
];
for (const r of rows) {
  const evidence = r.files.length ? r.files.map((f) => `\`${f}\` (${tierOf(f)})`).join('<br>') : r.s?.evidence ?? '';
  const residual = r.s ? `${r.s.reason}${r.s.owner ? ` Owner: ${r.s.owner}.` : ''}` : '';
  lines.push(`| ${r.id} | #${r.meta.issue} ${r.meta.cs} | ${esc(r.meta.text)} | ${r.state} | ${esc(evidence)} | ${esc(residual)} |`);
}
writeFileSync('docs/testing/acceptance-matrix.md', `${lines.join('\n')}\n`);
console.log(`acceptance matrix: wrote ${rows.length} rows; ${problems.length} missing`);
if (problems.length) console.log(`missing: ${problems.join(', ')}`);
